github:
  users: ["torvalds"]        # GitHub usernames/orgs to crawl
  max_repos: 3               # per user/org
  delay_seconds: 1.0         # polite sleep between requests/clones
  outdir: "data/raw/github"

  # Extraction mode: "repo" clones and reads all (text) files; "readme" only parses README from HTML
  mode: "repo"

  # Only used in mode: "repo"
  ignore_dirs: [".git", ".github", "node_modules", "venv", "__pycache__", "dist", "build"]
  ignore_exts: [".png", ".jpg", ".jpeg", ".gif", ".pdf", ".svg", ".zip", ".tar", ".gz", ".lock", ".toml"]
  max_file_mb: 1.0           # skip files larger than this
