github:
  users: ["kasramojallal1"]   # ← only your GitHub account
  max_repos: 50              # bump high enough to cover all public repos
  delay_seconds: 1.0
  outdir: "data/raw/github"

  # Crawl mode
  mode: "repo"                # "repo" = shallow-clone + file tree; "readme" = fast README-only

  # Repo-mode filters (to skip noise/binaries)
  ignore_dirs: [".git", ".github", "node_modules", "venv", "__pycache__", "dist", "build"]
  ignore_exts: [".png", ".jpg", ".jpeg", ".gif", ".pdf", ".svg", ".zip", ".tar", ".gz", ".lock", ".toml"]
  max_file_mb: 1.0
